
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Mar 07 16:22:07 GMT+01:00 2008
//----------------------------------------------------

package net.eclipse.why.editeur.lexer;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AT = 73;
  public static final int AS = 5;
  public static final int BOOL = 9;
  public static final int TIMES = 70;
  public static final int REAL = 38;
  public static final int GT = 65;
  public static final int ARROW = 60;
  public static final int TYPE = 45;
  public static final int PREDICATE = 33;
  public static final int IDENTIFIER = 86;
  public static final int NOTEQ = 67;
  public static final int GE = 66;
  public static final int VARIANT = 47;
  public static final int RAISE = 35;
  public static final int prec_exists = 97;
  public static final int prec_forall = 96;
  public static final int COMMA = 53;
  public static final int BARBAR = 82;
  public static final int LT = 63;
  public static final int EXCEPTION = 14;
  public static final int DONE = 11;
  public static final int PROP = 34;
  public static final int prec_if = 98;
  public static final int INTEGER_LITERAL = 88;
  public static final int LRARROW = 61;
  public static final int NOT = 29;
  public static final int FALSE = 17;
  public static final int LEFTBLEFTB = 79;
  public static final int LEFTB = 77;
  public static final int ARRAY = 4;
  public static final int LE = 64;
  public static final int LOGIC = 28;
  public static final int RIGHTBRIGHTB = 80;
  public static final int THEN = 42;
  public static final int PARAMETER = 32;
  public static final int prec_fun = 91;
  public static final int WRITES = 51;
  public static final int FLOAT_LITERAL = 89;
  public static final int prec_app = 101;
  public static final int GOAL = 22;
  public static final int FPI = 85;
  public static final int FUNCTION = 21;
  public static final int SLASH = 71;
  public static final int prec_simple = 92;
  public static final int TRUE = 43;
  public static final int FORALL = 19;
  public static final int PLUS = 68;
  public static final int STRING_LITERAL = 87;
  public static final int PERCENT = 72;
  public static final int QUOTE = 52;
  public static final int UNIT = 46;
  public static final int EXISTS = 15;
  public static final int RIGHTB = 78;
  public static final int EQUAL = 62;
  public static final int WHILE = 49;
  public static final int AXIOM = 7;
  public static final int COLONEQUAL = 59;
  public static final int FOR = 18;
  public static final int DO = 10;
  public static final int VOID = 48;
  public static final int TRY = 44;
  public static final int ELSE = 12;
  public static final int FUN = 20;
  public static final int DOT = 74;
  public static final int prec_recfun = 90;
  public static final int INT = 25;
  public static final int ABSURD = 2;
  public static final int prec_letrec = 93;
  public static final int RIGHTPAR = 55;
  public static final int prec_named = 95;
  public static final int SEMICOLON = 58;
  public static final int EOF = 0;
  public static final int BANG = 56;
  public static final int uminus = 100;
  public static final int MINUS = 69;
  public static final int LEFTPAR = 54;
  public static final int INVARIANT = 26;
  public static final int IN = 24;
  public static final int OR = 31;
  public static final int EXTERNAL = 16;
  public static final int error = 1;
  public static final int RIGHTSQ = 76;
  public static final int IF = 23;
  public static final int OF = 30;
  public static final int END = 13;
  public static final int prec_no_else = 94;
  public static final int ASSERT = 6;
  public static final int COLON = 57;
  public static final int AMPAMP = 83;
  public static final int READS = 37;
  public static final int prec_relation = 99;
  public static final int REF = 40;
  public static final int REC = 39;
  public static final int BEGIN = 8;
  public static final int prec_ident = 102;
  public static final int RETURNS = 41;
  public static final int RAISES = 36;
  public static final int BIGARROW = 84;
  public static final int AND = 3;
  public static final int BAR = 81;
  public static final int WITH = 50;
  public static final int LET = 27;
  public static final int LEFTSQ = 75;
}

